### ISSUE TITLE
Not compatible with Python 3.12.1

### ISSUE THREAD

**Issue by jredd96** [mackliet/church_of_jesus_christ_api#13]
First off, I want to say THANK YOU for writing this API. It is incredibly helpful for reducing my workload as an Executive Secretary.

With this issue I wanted to let you know that I was testing using the latest Python version (3.12.1) with this package, and it does not work. Without spending hours dissecting your implementations, it seems the issue is coming from the use of type hints/annotations. I get the following error when trying to import the module:

```
import church_of_jesus_christ_api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/church_of_jesus_christ_api/__init__.py", line 1, in <module>
    from .church_of_jesus_christ_api import *
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/church_of_jesus_christ_api/church_of_jesus_christ_api.py", line 17, in <module>
    import requests
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/__init__.py", line 147, in <module>
    from . import packages, utils
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/utils.py", line 24, in <module>
    from . import certs
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/certs.py", line 14, in <module>
    from certifi import where
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/certifi/__init__.py", line 1, in <module>
    from .core import contents, where
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/certifi/core.py", line 16, in <module>
    from importlib.resources import as_file, files
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/resources/__init__.py", line 3, in <module>
    from ._common import (
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/resources/_common.py", line 80, in <module>
    @resolve.register
     ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/functools.py", line 879, in register
    argname, cls = next(iter(get_type_hints(func).items()))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'items'
```

Maybe someday I will be savvy enough to fork this or submit a pull request to allow for forward compatibility, but for now I will just stick with falling back on my Python 3.9 interpreter.

**Comment by IsaacsLab42** [comment]
I also ran into this issue. I found that the culprit is line 13 in `church_of_jesus_christ.py`:

```python
typing.get_type_hints = lambda obj, *unused: obj
```

When I removed that line then this API worked properly in Python 3.12. I don't know the ripple effects, or how it would affect other versions of Python, so I didn't submit a pull request.

**Comment by mackliet** [comment]
I will go ahead and make that change. I didn't recall why I needed to add
this, but I vaguely remember needing to do something with the type hints to
make the documentation appear like I wanted it to. Maybe that's what this
has to do with, I'm not sure

**Comment by mackliet** [comment]
This should be fixed now with your latest PR. Thanks for making that change for me!
